joseviictor/oficinapp

- src/clientes-cria_novo_cliente.py
- src/clientes-imprime_lista_de_clientes.py
- src/clientes.py
> Movidas as funções dos clientes para clients.py e removidos os ficheiros clientes-*.py

- src/clientes.py
> Implementação básica da função para criar novo cliente.

- src/clientes.py
> Implementacao basica da função para imprimir lista de clientes

- src/clientes.py
- src/faturas.py
> Implementação básica da função para imprimir lista de faturas.

- src/io_ficheiros.py
- src/main.py
- src/materiais.py
- src/servicos.py
Foram também implementadas as funções para criação, exclusão e impressão de materiais e serviços.
> Criados os ficheiros dos materiais e serviços 

- src/faturas.py
- src/main.py
> Criada a função para excluir faturas.

- src/clientes.py
- src/main.py
> Implementada a funçao de excluir clientes

- src/clientes.py
> fix de alguns erros de tipografia

- src/bd.py
Adição de uma função em que inserimos o nome da tabela e imprime todos os dados dessa tabela.
Adição de uma função em que inserimos o nome da tabela e imprime todos os campos dessa tabela.
> Adiçao das funções para obter os registos e os campos de uma tabela generica.

- src/clientes.py
- src/main.py
Correção no ficheiro main.py pois faltava a declaração das funções.
Pequenas alterações no ficheiro clientes.py
> Implementaçaão CRUD do cliente no menu principal e ficheiro individual

- src/main.py
- src/veiculos.py
Foram adicionadas funções CRUD para o veiculo no seu ficheiro.
Declaração das funçoes criadas para o veiculo na sua secção do menu.
> Implementaçaão CRUD de veículos

- src/main.py
- src/ordens_reparacao.py
Foram adicionadas funções CRUD para as ordens de reparação no seu ficheiro.
Declaração das funções criadas para as ordens de reparação na sua secção do menu.
> Implementaçaão CRUD das ordens de reparação

- src/faturas.py
- src/main.py
Foram adicionadas funções CRUD para as faturas no seu ficheiro.
Declaração das funções criadas para as faturas na sua secção do menu.
> Implementaçaão CRUD das Faturas

- src/main.py
- src/materiais.py
Foram adicionadas funções CRUD para os materiais no seu ficheiro.
Declaração das funções criadas para  os materiais na sua secção do menu.
> Implementaçaão CRUD dos materiais

- src/main.py
- src/servicos.py
Foram adicionadas funções CRUD para os Serviços no seu ficheiro.
Declaração das funções criadas para os Serviços na sua secção do menu.
> Implementaçaão CRUD dos Serviços

- src/bd.py
- src/clientes.py
- src/faturas.py
- src/main.py
- src/materiais.py
- src/ordens_reparacao.py
- src/servicos.py
- src/veiculos.py
Funçao que recebe o nome da tabela, condiçoes e valores a defenir para que assum atualize os dados na tabela selecionada.
> implementaçaão de uma funçao de atualizar para todas as tabela generalizada

- src/bd.py
- src/clientes.py
- src/faturas.py
- src/main.py
- src/materiais.py
- src/ordens_reparacao.py
- src/servicos.py
- src/veiculos.py
Funçao que recebe o nome da tabela, condiçoes e valores a defenir para que assim apage os dados na tabela selecionada.
> implementaçaão de uma funçao de apagar dados para todas as tabelas generalizada

- src/bd.py
- src/clientes.py
- src/faturas.py
- src/main.py
- src/materiais.py
- src/ordens_reparacao.py
- src/servicos.py
- src/veiculos.py
Limpeza de algumas linhas desnecessarias e correta utilização dos códigos.
> Limpeza de código e pequenas melhorias

- src/bd.py
- src/io_terminal.py
- src/main.py
atualização da funçao de imprimir de forma a que seja mais percetivel e mais bonita a exibiçao de dados de uma tabela.
> Alteração da forma de exibiçao para algo mais legivel

- src/bd.py
- src/clientes.py
- src/faturas.py
- src/io_terminal.py
- src/main.py
- src/materiais.py
- src/ordens_reparacao.py
- src/servicos.py
- src/veiculos.py
adição de comentarios em docstring para futura melhoria na real documentação
> Documentação util das funções
